from pathlib import Path

import joblib
import pandas as pd
import streamlit as st


st.set_page_config(
    page_title="Health Insurance Cost Predictor",
    page_icon="🏥",
    layout="centered",
)

APP_DIR = Path(__file__).resolve().parent


@st.cache_resource
def load_artifacts():
    files = {
        "scaler": "scaler.pkl",
        "gender_encoder": "label_encoder_gender.pkl",
        "diabetic_encoder": "label_encoder_diabetic.pkl",
        "smoker_encoder": "label_encoder_smoker.pkl",
        "model": "best_model.pkl",
    }

    missing = [filename for filename in files.values()
               if not (APP_DIR / filename).is_file()]
    if missing:
        raise FileNotFoundError(
            f"Missing model file(s) in {APP_DIR}: {', '.join(missing)}"
        )

    return {
        key: joblib.load(APP_DIR / filename)
        for key, filename in files.items()
    }


# Page styling
st.markdown(
    """
    <style>
    .stApp,
    [data-testid="stAppViewContainer"],
    [data-testid="stHeader"] {
        background: #000000;
        color: #ffffff;
    }

    .stApp h1, .stApp h2, .stApp h3,
    .stApp p, .stApp label, .stApp span,
    [data-testid="stCaptionContainer"] {
        color: #ffffff;
    }

    .block-container {
        max-width: 900px;
        padding-top: 2rem;
        padding-bottom: 3rem;
    }

    div[data-testid="stForm"] {
        background: #111111;
        border: 1px solid #444444;
        border-radius: 16px;
        padding: 1.25rem;
    }

    input, textarea,
    [data-baseweb="select"] > div {
        background-color: #222222;
        color: #ffffff;
    }

    div[data-testid="stFormSubmitButton"] > button {
        background-color: #333333;
        color: #ffffff;
        border: 1px solid #777777;
        border-radius: 10px;
        font-weight: 600;
    }

    div[data-testid="stFormSubmitButton"] > button:hover {
        background-color: #555555;
        border-color: #ffffff;
    }

    [data-testid="stAlert"] {
        background-color: #171717;
        color: #ffffff;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

try:
    artifacts = load_artifacts()
except FileNotFoundError as error:
    st.error(str(error))
    st.stop()

scaler = artifacts["scaler"]
le_gender = artifacts["gender_encoder"]
le_diabetic = artifacts["diabetic_encoder"]
le_smoker = artifacts["smoker_encoder"]
model = artifacts["model"]

st.title("🏥 Health Insurance Cost Predictor")
st.caption("Enter the details below to estimate an insurance payment.")
st.info(
    "This estimate is generated by a machine-learning model and is for "
    "informational purposes only."
)

with st.form("input_form"):
    st.subheader("Personal and health details")
    col1, col2 = st.columns(2)

    with col1:
        age = st.number_input("Age", min_value=0, max_value=100, value=40)
        bmi = st.number_input(
            "BMI", min_value=10.0, max_value=60.0, value=25.0, step=0.1
        )
        children = st.number_input(
            "Number of children", min_value=0, max_value=8, value=0
        )

    with col2:
        bloodpressure = st.number_input(
            "Blood pressure", min_value=60, max_value=200, value=120
        )
        gender = st.selectbox("Gender", options=le_gender.classes_)
        diabetic = st.selectbox("Diabetic", options=le_diabetic.classes_)
        smoker = st.selectbox("Smoker", options=le_smoker.classes_)

    submitted = st.form_submit_button(
        "Estimate payment", type="primary", use_container_width=True
    )

if submitted:
    input_data = pd.DataFrame(
        {
            "age": [age],
            "gender": [gender],
            "bmi": [bmi],
            "bloodpressure": [bloodpressure],
            "diabetic": [diabetic],
            "children": [children],
            "smoker": [smoker],
        }
    )

    try:
        input_data["gender"] = le_gender.transform(input_data["gender"])
        input_data["diabetic"] = le_diabetic.transform(input_data["diabetic"])
        input_data["smoker"] = le_smoker.transform(input_data["smoker"])

        numeric_columns = ["age", "bmi", "bloodpressure", "children"]
        input_data[numeric_columns] = scaler.transform(input_data[numeric_columns])

        prediction = float(model.predict(input_data)[0])
        st.session_state["prediction_result"] = {
            "amount": prediction,
            "details": {
                "Age": age,
                "BMI": bmi,
                "Blood pressure": bloodpressure,
                "Children": children,
                "Gender": gender,
                "Diabetic": diabetic,
                "Smoker": smoker,
            },
        }
    except (ValueError, KeyError) as error:
        st.error(f"Could not generate a prediction. Check the model inputs: {error}")

result = st.session_state.get("prediction_result")

if result:
    st.divider()
    st.subheader("Your estimate")
    st.metric("Estimated insurance payment", f"₵{result['amount']:,.2f}")

    with st.expander("Review entered details"):
        st.table(
            pd.DataFrame(
                result["details"].items(),
                columns=["Input", "Value"],
            )
        )

    report = pd.DataFrame(
        [{"Estimated payment": result["amount"], **result["details"]}]
    )
    st.download_button(
        "Download prediction report",
        data=report.to_csv(index=False).encode("utf-8"),
        file_name="insurance_prediction.csv",
        mime="text/csv",
    )